name: gunita20
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.6.2 #provided automatically by flutter. if ever; error. manually get from pub.dev
  firebase_core: ^2.8.0 #provided automatically by flutter. if ever; error. manually get from pub.dev
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  file_picker: ^4.1.0 #added for jasper's add photo screen/function
  get: ^4.6.5
  date_time_picker: ^2.0.0
  flutter_local_notifications: ^12.0.0
  image_picker: ^0.8.9
  cached_network_image: ^3.1.0
  firebase_storage: ^11.2.3
  transparent_image: ^2.0.1
  photo_view: ^0.14.0
  mask_text_input_formatter: ^2.0.0
  table_calendar: ^3.0.1 # Use the latest version
  carousel_slider: ^4.2.1
  image: ^4.0.17
  shimmer: ^2.0.0
  audioplayers : ^0.20.1
  shared_preferences: ^2.1.0
  confetti: ^0.7.0    
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
 
  
  

dev_dependencies:
flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0



# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Magdelin
      fonts:
        - asset: fonts/Magdelin-Bold.otf
        - asset: fonts/MagdelinAlt-Medium.otf
        - asset: fonts/MagdelinAlt-Regular.otf
        - asset: fonts/MagdelinAlt-Text.otf

    - family: kg_inimitable_original
      fonts:
        - asset: fonts/kg_inimitable_original.ttf

    - family: purple_smile
      fonts:
        - asset: fonts/purple_smile.ttf


  uses-material-design: true

  assets:
  - assets/images/





  